name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: go test -v ./... -coverprofile=cover.out

      - name: Code coverage
        uses: paambaati/codeclimate-action@v2.5.7
        env:
          CC_TEST_REPORTER_ID: b4ed4bd07174cfdde53c99b916ed25087cee93bfeb92c17c5720df4b73b470b0
        with:
          coverageCommand: go tool cover -html=cover.out -o coverage.html
          debug: true
